<?php
/** @var \Omnipro\Blog\Block\Blog $block */

use PayPal\Braintree\Block\Adminhtml\Virtual\Script;

/** @var \Omnipro\Blog\ViewModel\BlogViewModel $viewModel
*/

$viewModel = $block->getData('view_model');
$items = $viewModel->getOpinions();
$items = array_reverse($items);
?>
<!-- <script>
    const title = document.getElementById("title");
    const title = document.getElementById("content");
    const title = document.getElementById("email");
    const title = document.getElementById("image");

    const procesarDatos = (e) =>{
        e.preventDefault();
        if(!title.trim()){
            error = "Titulo vacío!!";
            return;
        }
    }

</script> -->

<div class="container mt-3 justify-content-center">
    <div class="row mt-3 mb-3 justify-content-center">
        <div class="col-12">
        <h1 class="text-center"> <?= $block->escapeHtmlAttr(__('My spectacular blog')) ?></h1>
        </div>
        <div class="col-12">
        <h4 class="text-center font-italic"><?= $block->escapeHtmlAttr(__('A totally false statement')) ?></h4>
        </div>
    </div>
</div>
    <div class="container mt-3 mb-3 bg-light justify-content-center rounded">
        <div class="row mt-3">
            <div class="col-6">
                <h4><?= $block->escapeHtmlAttr(__('New blog post')) ?></h4>
            </div>
        </div>
        <form method="POST" action="<?= $block->getUrl('blog/createblog/createblog'); ?>">
        <div class="row mt-3">
            <div class="col-10 col-sm-10 col-xs-10 col-md-10 col-lg-10 col-xl-7 col-xxl-7">
                <input required="true" id="title" class="form-control" type="text" name="title"
                 placeholder="My post title" data-validate="{required:true, 'validate-title':true}"/>
            </div>
            
        </div>
        <div class="row mt-3">
            <div class="col-10 col-sm-10 col-xs-10 col-md-10 col-lg-10 col-xl-7 col-xxl-7">
                <textarea required="true" id="content" class="form-control" type="text" name="content" 
                placeholder="Here all my important post text" rows="3" 
                data-validate="{required:true, 'validate-content':true}"></textarea>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-8 col-sm-8 col-xs-7 col-md-7 col-lg-7 col-xl-4 col-xxl-4">
            <input required="true" id="email" class="form-control" type="email" name="email" 
            placeholder="Email Address" data-validate="{required:true, 'validate-email':true}"/>
        </div>
        </div>
        <div class="row mt-3 mb-3">
            <div class="col-10 col-sm-10 col-xs-10 col-md-10 col-lg-10 col-xl-7 col-xxl-7">
                <input required="true" id="image" class="form-control" type="file" name="image" 
                 accept="image/png, image/gif, image/jpeg" data-validate="{required:true, 'validate-image':true}"/>
                <input type="hidden" name="form_key" value="<?php echo $block->getFormKey() ?>" />
            </div>
        </div>
        <div class="row mt-3 mb-3">
            <div class="col-2 col-sm-2 col-xs-2 col-md-2 col-lg-2 col-xl-5 col-xxl-5">
                <button class="btn btn-primary" type="submit"><?= $block->escapeHtmlAttr(__('Save post')) ?></button>
            </div>
        </div>
    </div>

<?php foreach ($items as $opinion): ?>
<div class="container  mt-3 rounded">
    <div class="row mt-5 justify-content-start ">
        <div class="col-9 col-sm-9 col-xs-9 col-md-9 col-lg-9 col-xl-7 col-xxl-7 rounded mt-3 bg-light" >
            <h3 class="justify"> <?= $opinion['title'] ?> </h3>
        </div>
        <div class=" col-3 col-sm-3 col-xs-3 col-md-3 col-lg-3 col-xl-2 col-xxl-2 rounded mt-3 bg-light">
            <h4 class="text-right"><?= $opinion['fecha'] ?></h4>
        </div>
    </div>
    <div class="row justify-content-start">
        <div class="col-2 col-sm-2 col-xs-2 col-md-2 col-lg-2 col-xl-2 col-xxl-2 rounded mb-3 bg-light">
            <img src="<?= $opinion['image_url'] ?>" class="img-fluid rounded" alt="image">  
        </div>
        <div class="col-10 col-sm-10 col-xs-10 col-md-10 col-lg-10 col-xl-7 col-xxl-7 rounded  mb-3 bg-light">
            <h5 class="text-justify justify">  <?= $opinion['opinion'] ?> </h5>
        </div>
        
    </div>
</div>
<?php endforeach; ?>

