<?php
/** @var \Magento\Framework\View\Element\Template $block */


?>

<div class="row">
    <div class="col-md-8">
        <form method="POST"
              action="<?= $block->getUrl('blog/createblog/createblog'); ?>"
              >
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Fill Detail')) ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                escapeHtmlAttr(__('Titulo')) ?></span></label>
                            <div class="control">
                                <input name="title" id="title" title="title" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="content"><span><?= $block->
                                escapeHtmlAttr(__('Contenido')) ?></span></label>
                            <div class="control">
                                <input name="content" id="content" title="content" value="" class="input-text" type="text"
                                       data-validate="{required:true">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                escapeHtmlAttr(__('Email')) ?></span></label>
                            <div class="control">
                                <input name="email" id="email" title="Email" value="" class="input-text" type="email"
                                       data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        
                        <div class="field name required">
                            <label class="label" for="profile_pic">Selecione la imagen </label>
                            <input type="file" id="profile_pic" name="profile_pic" value=""
                                accept=".jpg, .jpeg, .png" data-validate="{required:true}">
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save"><span><?= $block->
                        escapeHtmlAttr(__('Save')) ?></span></button>
                </div>
            </div>
        </form>
    </div>
</div>

